services:
  app:
    image: node:16-alpine
    container_name: ${PROJECT_NAME}-dev-container
    working_dir: /usr/${PROJECT_NAME}
    command: sh -c "npm install && npm run debug"
    networks:
      - dev-network
    ports:
      - 3018:3018
      - 9229:9229
    restart: on-failure
    environment:
      - SERVICE_NAME=${PROJECT_NAME}

      - NODE_ENV=development
      - PORT=3018
      - DB_HOST=

      - NEW_RELIC_ENABLED=false
      - NEW_RELIC_APP_NAME=${PROJECT_NAME}-development
      - NEW_RELIC_LICENSE_KEY=
    volumes:
      - ./dist/:/usr/${PROJECT_NAME}/
      - ./package.json:/usr/${PROJECT_NAME}/package.json
      - ./package-lock.json:/usr/${PROJECT_NAME}/package-lock.json
      - ./.npmrc:/usr/${PROJECT_NAME}/.npmrc

networks:
  dev-network:
    driver: bridge
